package main

var Cards = []Card{
	{ID: "1", Name: "The Fool", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "0", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/fool.png"},
	{ID: "2", Name: "The Magician", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "1", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/magician.png"},
	{ID: "3", Name: "The High Priestess", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "2", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/high_priestess.png"},
	{ID: "4", Name: "The Empress", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "3", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/empress.png"},
	{ID: "5", Name: "The Emperor", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "4", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/emperor.png"},
	{ID: "6", Name: "The Hierophant", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "5", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/hierophant.png"},
	{ID: "7", Name: "The Lovers", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "6", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/lovers.png"},
	{ID: "8", Name: "The Chariot", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "7", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/chariot.png"},
	{ID: "9", Name: "Strength", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "8", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/strength.png"},
	{ID: "10", Name: "The Hermit", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "9", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/hermit.png"},
	{ID: "11", Name: "The Wheel of Fortune", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "10", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/wheel_of_fortune.png"},
	{ID: "12", Name: "Justice", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "11", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/justice.png"},
	{ID: "13", Name: "The Hanged Man", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "12", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/hanged_man.png"},
	{ID: "14", Name: "Death", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "13", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/death.png"},
	{ID: "15", Name: "Temperance", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "14", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/temperance.png"},
	{ID: "16", Name: "The Devil", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "15", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/devil.png"},
	{ID: "17", Name: "The Tower", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "16", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/tower.png"},
	{ID: "18", Name: "The Star", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "17", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/star.png"},
	{ID: "19", Name: "The Moon", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "18", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/moon.png"},
	{ID: "20", Name: "The Sun", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "19", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/sun.png"},
	{ID: "21", Name: "Judgement", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "20", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/judgement.png"},
	{ID: "22", Name: "The World", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "21", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/world.png"},
	{ID: "23", Name: "Ace of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "Ace", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/ace_of_cups.png"},
	{ID: "24", Name: "Two of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "2", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/two_of_cups.png"},
	{ID: "25", Name: "Three of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "3", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/three_of_cups.png"},
	{ID: "26", Name: "Four of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "4", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/four_of_cups.png"},
	{ID: "27", Name: "Five of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "5", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/five_of_cups.png"},
	{ID: "28", Name: "Six of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "6", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/six_of_cups.png"},
	{ID: "29", Name: "Seven of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "7", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/seven_of_cups.png"},
	{ID: "30", Name: "Eight of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "8", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/eight_of_cups.png"},
	{ID: "31", Name: "Nine of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "9", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/nine_of_cups.png"},
	{ID: "32", Name: "Ten of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "10", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/ten_of_cups.png"},
	{ID: "33", Name: "Page of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "Page", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/page_of_cups.png"},
	{ID: "34", Name: "Knight of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "Knight", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/knight_of_cups.png"},
	{ID: "35", Name: "Queen of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "Queen", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/queen_of_cups.png"},
	{ID: "36", Name: "King of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "King", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/king_of_cups.png"},
	{ID: "37", Name: "Ace of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "Ace", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/ace_of_wands.png"},
	{ID: "38", Name: "Two of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "2", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/two_of_wands.png"},
	{ID: "39", Name: "Three of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "3", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/three_of_wands.png"},
	{ID: "40", Name: "Four of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "4", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/four_of_wands.png"},
	{ID: "41", Name: "Five of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "5", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/five_of_wands.png"},
	{ID: "42", Name: "Six of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "6", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/six_of_wands.png"},
	{ID: "43", Name: "Seven of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "7", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/seven_of_wands.png"},
	{ID: "44", Name: "Eight of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "8", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/eight_of_wands.png"},
	{ID: "45", Name: "Nine of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "9", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/nine_of_wands.png"},
	{ID: "46", Name: "Ten of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "10", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/ten_of_wands.png"},
	{ID: "47", Name: "Page of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "Page", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/page_of_wands.png"},
	{ID: "48", Name: "Knight of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "Knight", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/knight_of_wands.png"},
	{ID: "49", Name: "Queen of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "Queen", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/queen_of_wands.png"},
	{ID: "50", Name: "King of Wands", Arcana: "Minor Arcana", Suit: "Wands", Rank: "King", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/king_of_wands.png"},
	{ID: "51", Name: "Ace of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "Ace", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/ace_of_swords.png"},
	{ID: "52", Name: "Two of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "2", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/two_of_swords.png"},
	{ID: "53", Name: "Three of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "3", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/three_of_swords.png"},
	{ID: "54", Name: "Four of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "4", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/four_of_swords.png"},
	{ID: "55", Name: "Five of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "5", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/five_of_swords.png"},
	{ID: "56", Name: "Six of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "6", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/six_of_swords.png"},
	{ID: "57", Name: "Seven of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "7", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/seven_of_swords.png"},
	{ID: "58", Name: "Eight of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "8", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/eight_of_swords.png"},
	{ID: "59", Name: "Nine of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "9", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/nine_of_swords.png"},
	{ID: "60", Name: "Ten of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "10", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/ten_of_swords.png"},
	{ID: "61", Name: "Page of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "Page", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/page_of_swords.png"},
	{ID: "62", Name: "Knight of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "Knight", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/knight_of_swords.png"},
	{ID: "63", Name: "Queen of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "Queen", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/queen_of_swords.png"},
	{ID: "64", Name: "King of Swords", Arcana: "Minor Arcana", Suit: "Swords", Rank: "King", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/king_of_swords.png"},
	{ID: "65", Name: "Ace of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "Ace", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/ace_of_pentacles.png"},
	{ID: "66", Name: "Two of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "2", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/two_of_pentacles.png"},
	{ID: "67", Name: "Three of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "3", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/three_of_pentacles.png"},
	{ID: "68", Name: "Four of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "4", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/four_of_pentacles.png"},
	{ID: "69", Name: "Five of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "5", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/five_of_pentacles.png"},
	{ID: "70", Name: "Six of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "6", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/six_of_pentacles.png"},
	{ID: "71", Name: "Seven of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "7", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/seven_of_pentacles.png"},
	{ID: "72", Name: "Eight of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "8", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/eight_of_pentacles.png"},
	{ID: "73", Name: "Nine of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "9", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/nine_of_pentacles.png"},
	{ID: "74", Name: "Ten of Pentacles", Arcana: "Minor Arcana", Suit: "Major Arcana", Rank: "10", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/ten_of_pentacles.png"},
	{ID: "75", Name: "Page of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "Page", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/page_of_pentacles.png"},
	{ID: "76", Name: "Knight of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "Knight", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/knight_of_pentacles.png"},
	{ID: "77", Name: "Queen of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "Queen", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/queen_of_pentacles.png"},
	{ID: "78", Name: "King of Pentacles", Arcana: "Minor Arcana", Suit: "Pentacles", Rank: "King", KeyWords: []string{"sgsd", "sds"}, Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/king_of_pentacles.png"},
	// {ID: "1", Name: "The Fool", Arcana: "Major Arcana", Suit: "Major Arcana", Rank: "0", Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/fool.png"},
	// {ID: "78", Name: "Ace of Cups", Arcana: "Minor Arcana", Suit: "Cups", Rank: "Ace", Image: "https://tarotcardbucket37921.s3.amazonaws.com/tarotCards/ace_of_cups.png"},
	// Add more cards as needed
}
